#!/bin/bash

# DSPy Agentic Loop Demo Runner

echo "🦙 DSPy Agentic Loop Demo"
echo "========================="
echo ""

# Parse command line arguments
DEBUG_MODE=false
TOOL_SET=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --debug)
            DEBUG_MODE=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [TOOL_SET] [OPTIONS]"
            echo ""
            echo "Arguments:"
            echo "  TOOL_SET             Tool set to load (default: productivity)"
            echo "                       Available: treasure_hunt, productivity, ecommerce"
            echo ""
            echo "Options:"
            echo "  --debug              Enable debug mode (show prompts and LLM responses)"
            echo "  -h, --help           Show this help message"
            echo ""
            echo "Examples:"
            echo "  ./run_demo.sh                    # Default: productivity tool set"
            echo "  ./run_demo.sh treasure_hunt      # Treasure hunt tool set"
            echo "  ./run_demo.sh productivity --debug  # Productivity tools with debug"
            echo "  ./run_demo.sh ecommerce          # E-commerce tools"
            exit 0
            ;;
        --*)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
        *)
            # This is the tool set argument
            if [ -z "$TOOL_SET" ]; then
                TOOL_SET="$1"
            else
                echo "Error: Multiple tool sets specified"
                echo "Use --help for usage information"
                exit 1
            fi
            shift
            ;;
    esac
done

# Set debug mode
if [ "$DEBUG_MODE" = true ]; then
    export DSPY_DEBUG=true
    echo "🔍 Debug mode enabled"
    echo "  • Will show prompts generated by DSPy"
    echo "  • Will show raw LLM responses"
    echo "  • Will show agentic loop reasoning"
    echo ""
fi

# Run setup if needed
if [ ! -d ".venv" ] || [ ! -f ".env" ]; then
    echo "Running setup first..."
    ./setup.sh
    if [ $? -ne 0 ]; then
        echo "Setup failed. Please fix the issues and try again."
        exit 1
    fi
    echo ""
fi

# Run the demo
echo "🚀 Running agentic loop demo..."
if [ -n "$TOOL_SET" ]; then
    echo "📦 Tool set: $TOOL_SET"
else
    echo "📦 Tool set: productivity (default)"
fi
echo ""

# Build command
CMD="poetry run python -m agentic_loop.agent_loop_demo"
if [ -n "$TOOL_SET" ]; then
    CMD="$CMD $TOOL_SET"
fi

# Execute command
$CMD

if [ "$DEBUG_MODE" = true ]; then
    echo ""
    echo "💡 TIP: You can also use dspy.inspect_history() in your code"
    echo "   to see the prompts and responses at any point."
    echo ""
    echo "Note: You can permanently enable debug by setting DSPY_DEBUG=true in .env"
fi