#!/bin/bash

# Simple DSPy Tool Selection Demo Runner

echo "🦙 DSPy Tool Selection Demo"
echo "=========================="
echo ""

# Parse command line arguments
DEBUG_MODE=false
PREDICT_MODE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --debug)
            DEBUG_MODE=true
            shift
            ;;
        --predict)
            PREDICT_MODE="predict"
            shift
            ;;
        --cot|--chain-of-thought)
            PREDICT_MODE="cot"
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --debug              Enable debug mode (show prompts and LLM responses)"
            echo "  --predict            Use Predict mode (direct prediction)"
            echo "  --cot                Use Chain of Thought mode (default)"
            echo "  --chain-of-thought   Same as --cot"
            echo "  -h, --help           Show this help message"
            echo ""
            echo "Examples:"
            echo "  ./run_demo.sh                    # Default: Chain of Thought mode"
            echo "  ./run_demo.sh --debug            # Chain of Thought with debug output"
            echo "  ./run_demo.sh --predict          # Predict mode"
            echo "  ./run_demo.sh --predict --debug  # Predict mode with debug output"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Set debug mode
if [ "$DEBUG_MODE" = true ]; then
    export DSPY_DEBUG=true
    echo "🔍 Debug mode enabled"
    echo "  • Will show prompts generated by DSPy"
    echo "  • Will show raw LLM responses"
    echo "  • Will show how DSPy parses structured outputs"
    echo ""
fi

# Set predict mode
if [ "$PREDICT_MODE" = "predict" ]; then
    export DSPY_USE_PREDICT=true
    echo "🎯 Running in Predict mode (direct prediction)"
elif [ "$PREDICT_MODE" = "cot" ]; then
    export DSPY_USE_PREDICT=false
    echo "🤔 Running in Chain of Thought mode (step-by-step reasoning)"
else
    # Default to Chain of Thought
    export DSPY_USE_PREDICT=false
    echo "🤔 Running in Chain of Thought mode (step-by-step reasoning)"
fi

echo ""

# Run setup if needed
if [ ! -d ".venv" ] || [ ! -f ".env" ]; then
    echo "Running setup first..."
    ./setup.sh
    if [ $? -ne 0 ]; then
        echo "Setup failed. Please fix the issues and try again."
        exit 1
    fi
    echo ""
fi

# Run the demo
echo "🚀 Running demo..."
echo ""
poetry run python -m tool_selection.multi_demo

if [ "$DEBUG_MODE" = true ]; then
    echo ""
    echo "💡 TIP: You can also use dspy.inspect_history() in your code"
    echo "   to see the prompts and responses at any point."
    echo ""
    echo "Note: You can permanently enable debug by setting DSPY_DEBUG=true in .env"
fi